theme = "air"
baseurl = "http://example.org/"
title = "Air - Free Website Template, Free HTML5 Template by freehtml5.co"
languageCode = "en-us"

# Menu items.
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 2

[[menu.main]]
    name = "Sign Up"
    url = "/signup/"
    weight = 3

[params]
    # Text for the title.html partial.
    [params.title]
        title = "Algorithm-based tools for the value investor."
        subtitle = "Subscribe and invest with confidence."
        button_text = "Sign Up"
        button_href = "signup"

    # Text for the features.html partial.
    [[params.feature.item]]
        icon_name = "eye-blocked"
        title = "Keep your info private"
        details = "ShortRoad makes recommendations and lets you decide the final call. No need to hand over sensitive bank or investment account information."

    [[params.feature.item]]
        icon_name = "home3"
        title = "Designed for Stability"
        details = "No need to check your stocks app every five minutes. ShortRoad chooses companies you can buy and hold in for years."

    [[params.feature.item]]
        icon_name = "stats-bars"
        title = "Analytics you can trust"
        details = "Don't wonder what's behind the algorithm. ShortRoad will explain in plain English why it made the calls it did."

    [[params.feature.item]]
        icon_name = "mobile2"
        title = "Platform Agnostic"
        details = "ShortRoad is designed so you can check in through any computer, tablet, or smartphone."

    [[params.feature.item]]
        icon_name = "books"
        title = "Trusted Practices"
        details = "ShortRoad's algorithms are based off of the legends of value investing, such as Warren Buffett and Ben Graham."

    [[params.feature.item]]
        icon_name = "happy2"
        title = "Made for You"
        details = "ShortRoad places your happiness first, not that of your broker or your trader."

    # Text for wireframe.html partial
    [params.wireframe]
        title = "Our mission is to help you be a better investor."
        text1 = "Today, two types of financial companies exist today: the hyper-advanced startups that use machine learning to predict the next tick of the Dow Jones, and the wealth management firm that requires a $100,000 minimum deposit and charges $400 an hour for advice."

        text2 = "So how much of the money you invest with either of them ends up back in your own pocket?"

        text3 = "We think there's a third way. You don't need the latest technology or data or mathematical models to make positive financial decisions for yourself and your loved ones. You also don't need to have a $100,000 minimum deposit. All you need is patience and insight. Our deal with you is that you provide the patience, and we'll provide the insight."

        card_title = "What ShortRoad was built for: to help you"
        card_text = "I used to read 500 pages worth of financial statements a day, trying to make sure I didn't miss anything important for my fund. With ShortRoad, all I needed to do is set my preferences in the app and wait for my phone to buzz me about a company. It really was that easy."
        card_name = "Wilburn Preston"
        card_credentials = "Index Fund Manager"

    # Text for the contact form within the contact.html partial.
    # Other text is provided via signup.md
    [params.contact_form]
        name_placeholder_text = "Name"
        email_placeholder_text = "Email"
        message_placeholder_text = "Message"
        submit_button_text = "Send Message"

    # Brand configuration.
    [params.brand]
        name = "ShortRoad"
        description = "Algorithm-based tools to provide value investors broad insights into today's markets, while saving time and effort in parsing financial statements."

    [params.address]
        street1 = "7315 Wisconsin Avenue"
        street2 = "Suite A113"
        city = "Bethesda"
        state = "MD"
        zipcode = "20814"

    [params.contact]
        phone = "248-860-6418"
        email = "yingw787@gmail.com"
        website = "shortroad.yingw787.com"

    [params.footer]
        title = "Sign up today!"
        description = "Be the first to hear about our initial release!"
        button_text = "Sign Up"
        button_href = "/signup"

    [params.copyright_statement]
        english = "All Rights Reserved."
