theme = "air"
baseurl = "http://example.org/"
title = "Air - Free Website Template, Free HTML5 Template by freehtml5.co"
languageCode = "en-us"

# Menu items.
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 2

[[menu.main]]
    name = "Sign Up"
    url = "/signup/"
    weight = 3

[params]
    # Text for the title.html partial.
    [params.title]
        title = "Algorithmic tools for the value investor."
        subtitle = "Subscribe and invest with confidence."
        button_text = "Sign Up"
        button_href = "signup"

    # Text for the features.html partial.
    [[params.feature.item]]
        icon_name = "eye-blocked"
        title = "Keep your info private"
        details = "ShortRoad makes recommendations and lets you decide the final call. No need to hand over sensitive bank or investment account information."

    [[params.feature.item]]
        icon_name = "home3"
        title = "Designed for Stability"
        details = "No need to check your stocks app every five minutes. ShortRoad chooses companies you can buy and hold in for years."

    [[params.feature.item]]
        icon_name = "stats-bars"
        title = "Analytics you can trust"
        details = "Don't wonder what's behind the algorithm. ShortRoad will explain in plain English why it made the calls it did."

    [[params.feature.item]]
        icon_name = "mobile2"
        title = "Platform Agnostic"
        details = "ShortRoad is designed so you can check in through any computer, tablet, or smartphone."

    [[params.feature.item]]
        icon_name = "books"
        title = "Trusted Practices"
        details = "ShortRoad's algorithms are based off of the legends of value investing, such as Warren Buffett and Ben Graham."

    [[params.feature.item]]
        icon_name = "happy2"
        title = "Made for You"
        details = "ShortRoad places your happiness first, not that of your broker or your trader."

    # Text for wireframe.html partial
    [params.wireframe]
        title = "Wireframe Connects the Underlying Conceptual Structure"
        text1 = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts far from the countries Vokalia and Consonantia, there live the blind texts."
        text2 = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts far from the countries Vokalia and Consonantia, there live the blind texts."
        text3 = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts far from the countries Vokalia and Consonantia, there live the blind texts. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts far from the countries Vokalia and Consonantia, there live the blind texts."

        card_title = "Wireframe Connects the Underlying Conceptual Structure"
        card_text = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts far from the countries Vokalia and Consonantia, there live the blind texts."
        card_name = "Louie Jie Mahusay"
        card_credentials = "CEO, Founder"

    # Text for the contact form within the contact.html partial.
    # Other text is provided via signup.md
    [params.contact_form]
        name_placeholder_text = "Name"
        email_placeholder_text = "Email"
        message_placeholder_text = "Message"
        submit_button_text = "Send Message"

    # Brand configuration.
    [params.brand]
        name = "ShortRoad"
        description = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit. Eos cumque dicta adipisci architecto culpa amet."

    [params.address]
        street1 = "7315 Wisconsin Avenue"
        street2 = "Suite A113"
        city = "Bethesda"
        state = "MD"
        zipcode = "20814"

    [params.contact]
        phone = "248-860-6418"
        email = "yingw787@gmail.com"
        website = "shortroad.yingw787.com"

    [params.footer]
        title = "Sign up today!"
        description = "Be the first to hear about our initial release!"
        button_text = "Sign Up"
        button_href = "/signup"

    [params.copyright_statement]
        english = "All Rights Reserved."
