theme = "air"
baseurl = "http://example.org/"
title = "Air - Free Website Template, Free HTML5 Template by freehtml5.co"
languageCode = "en-us"

# Menu items.
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 2

[[menu.main]]
    name = "Sign Up"
    url = "/signup/"
    weight = 3

[params]
    # Text for the title.html partial.
    [params.title]
        title = "API-first tools for the value investor."
        subtitle = "Integrate anywhere, invest with confidence."
        button_text = "Sign Up"
        button_href = "signup"

    # Text for the features.html partial.
    [[params.feature.item]]
        icon_name = "hotairballoon"
        title = "Marketing"
        details = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit."

    [[params.feature.item]]
        icon_name = "search"
        title = "Search Engine"
        details = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit."

    [[params.feature.item]]
        icon_name = "wallet"
        title = "Earn Money"
        details = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit."

    [[params.feature.item]]
        icon_name = "wine"
        title = "Entrepreneur"
        details = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit."

    [[params.feature.item]]
        icon_name = "genius"
        title = "Strategic Plan"
        details = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit."

    [[params.feature.item]]
        icon_name = "chat"
        title = "Support"
        details = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit."

    # Text for wireframe.html partial
    [params.wireframe]
        title = "Wireframe Connects the Underlying Conceptual Structure"
        text1 = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts far from the countries Vokalia and Consonantia, there live the blind texts."
        text2 = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts far from the countries Vokalia and Consonantia, there live the blind texts."
        text3 = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts far from the countries Vokalia and Consonantia, there live the blind texts. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts far from the countries Vokalia and Consonantia, there live the blind texts."

        card_title = "Wireframe Connects the Underlying Conceptual Structure"
        card_text = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts far from the countries Vokalia and Consonantia, there live the blind texts."
        card_name = "Louie Jie Mahusay"
        card_credentials = "CEO, Founder"

    # Text for the contact form within the contact.html partial.
    # Other text is provided via signup.md
    [params.contact_form]
        name_placeholder_text = "Name"
        email_placeholder_text = "Email"
        message_placeholder_text = "Message"
        submit_button_text = "Send Message"

    # Brand configuration.
    [params.brand]
        name = "ShortRoad"
        description = "Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit. Eos cumque dicta adipisci architecto culpa amet."

    [params.address]
        street1 = "7315 Wisconsin Avenue"
        street2 = "Suite A113"
        city = "Bethesda"
        state = "MD"
        zipcode = "20814"

    [params.contact]
        phone = "248-860-6418"
        email = "yingw787@gmail.com"
        website = "shortroad.yingw787.com"

    [params.footer]
        title = "Sign up today!"
        description = "Be the first to hear about our initial release!"
        button_text = "Sign Up"
        button_href = "/signup"

    [params.copyright_statement]
        english = "All Rights Reserved."
